name: "publish-gaelo-flow"

on:
  push:
    branches:
      - "*"
    tags:
      - "*"

jobs:
  build:
    name: "Build and publish"
    runs-on: ubuntu-latest
    steps:
      - name: "Build checkout"
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/pixilib/gaelo-viewers-stone
          tags: |
            type=ref,event=tag
            gaelo-flow-latest

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Download stone
        run: wget https://orthanc.uclouvain.be/downloads/linux-standard-base/stone-web-viewer/2.6/wasm-binaries.zip

      - run: mkdir stone
      - run: unzip wasm-binaries.zip -d ./stone

      - run: cp ./public/viewers/Stone/configuration-flow.json ./stone/wasm-binaries/StoneWebViewer/configuration.json

      - run: ls ./stone/wasm-binaries/StoneWebViewer

      - name: Login to github registery
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: "salimkanoun"
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          pull: true
          tags: ${{ steps.meta.outputs.tags }}

permissions:
  contents: read
  packages: write